services:
  frontend:
    image: fullstack-blog-frontend:dev
    ports:
      - "3000:3000"
    volumes:
      - ./app/vite-vue3/src:/usr/src/fullstack-blog/app/frontend/src
      - ./app/vite-vue3/vite.config.docker.ts:/usr/src/fullstack-blog/app/frontend/vite.config.ts
      - ./app/vite-vue3/index.html:/usr/src/fullstack-blog/app/frontend/index.html
      - ./app/vite-vue3/public:/usr/src/fullstack-blog/app/frontend/public
      - ./.prettierrc.json:/usr/src/fullstack-blog/.prettierrc.json
      - ./.prettierignore:/usr/src/fullstack-blog/.prettierignore
    environment:
      - NODE_ENV=development

  backend:
    image: fullstack-blog-backend:dev
    ports:
      - "8002:8002"
    volumes:
      - ./app/backend/src:/usr/src/fullstack-blog/app/backend/src
    environment:
      - NODE_ENV=development
      - PORT=8002

# 如果还有数据库或其他服务，也可以在这里添加
# ...
