services:
  mysql:
    restart: always
    image: mysql:8.4.2
    ports:
      - "3308:3306"
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_0900_ai_ci
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/init-scripts:/docker-entrypoint-initdb.d

#   cra-react18:
#     restart: always
#     image: fullstack-blog-cra-react18:dev
#     ports:
#       - "3002:3002"
#     volumes:
#       - ./app/cra-react18/src:/usr/src/fullstack-blog/app/cra-react18/src
#       - ./app/cra-react18/public:/usr/src/fullstack-blog/app/cra-react18/public
#       - ./app/cra-react18/config:/usr/src/fullstack-blog/app/cra-react18/config
#       - ./app/cra-react18/scripts:/usr/src/fullstack-blog/app/cra-react18/scripts
#       - ./.prettierrc.json:/usr/src/fullstack-blog/.prettierrc.json
#       - ./.prettierignore:/usr/src/fullstack-blog/.prettierignore
#     environment:
#       - NODE_ENV=development
#       - HOST=0.0.0.0
#       - PORT=3002
#       - CHOKIDAR_USEPOLLING=true
#       - DANGEROUSLY_DISABLE_HOST_CHECK=true

  vite-vue3:
    image: fullstack-blog-vite-vue3:dev
    ports:
      - "3000:3000"
    volumes:
      - ./app/vite-vue3/src:/usr/src/fullstack-blog/app/vite-vue3/src
      - ./app/vite-vue3/vite.config.docker.ts:/usr/src/fullstack-blog/app/vite-vue3/vite.config.ts
      - ./app/vite-vue3/index.html:/usr/src/fullstack-blog/app/vite-vue3/index.html
      - ./app/vite-vue3/public:/usr/src/fullstack-blog/app/vite-vue3/public
      - ./app/vite-vue3/.env:/usr/src/fullstack-blog/app/vite-vue3/.env
      - ./app/vite-vue3/.env.development:/usr/src/fullstack-blog/app/vite-vue3/.env.development
      - ./.prettierrc.json:/usr/src/fullstack-blog/.prettierrc.json
      - ./.prettierignore:/usr/src/fullstack-blog/.prettierignore
    environment:
      - NODE_ENV=development
      - VITE_APP_BACKEND_SERVER=http://172.22.192.1:8012
      - VITE_APP_SOCKET_SERVER=http://172.22.192.1:8012

#   express-server:
#     restart: always
#     image: fullstack-blog-express:dev
#     ports:
#       - "8002:8002"
#     volumes:
#       - ./app/express-server/src:/usr/src/fullstack-blog/app/express-server/src
#     environment:
#       - NODE_ENV=development
#       - PORT=8002
#       - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
#       - MYSQL_DATABASE=${MYSQL_DATABASE}
#       - WEB_SOCKET_WHITE_LIST=http://localhost:3000
#     working_dir: /usr/src/fullstack-blog/app/express-server
#     command: ["pnpm", "docker-dev"]
#     depends_on:
#       - mysql

#   nestjs-server:
#     restart: always
#     image: fullstack-blog-nestjs:dev
#     working_dir: /usr/src/fullstack-blog/app/nest-server
#     ports:
#       - "8012:8012"
#     volumes:
#       - ./app/nest-server/src:/usr/src/fullstack-blog/app/nest-server/src
#       - ./app/nest-server/tsconfig.json:/usr/src/fullstack-blog/app/nest-server/tsconfig.json
#       - ./app/nest-server/nest-cli.json:/usr/src/fullstack-blog/app/nest-server/nest-cli.json
#       - ./app/nest-server/package.json:/usr/src/fullstack-blog/app/nest-server/package.json
#     environment:
#       - NODE_ENV=development
#       - PORT=8012
#       - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
#       - MYSQL_DATABASE=${MYSQL_DATABASE}
#     command: pnpm dev
#     depends_on:
#       - mysql

volumes:
  mysql_data:
