services:
  vite-vue3:
    build:
      target: vite-vue3-frontend
    image: fullstack-blog-vite-vue3:latest
    ports:
      - "3000:80"
    environment:
      - BACKEND_PORT=8002
    command: /bin/bash -c "envsubst '$$BACKEND_PORT' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && cat /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  express-server:
    build:
      target: express-backend
    image: fullstack-blog-express:latest
    ports:
      - "8002:8002"
    volumes:
      - ./app/express-server/src/config/env.js:/usr/src/fullstack-blog/app/express-server/src/config/env.js
      - ./app/express-server/src/config/prod.env.js:/usr/src/fullstack-blog/app/express-server/src/config/prod.env.js
    environment:
      - NODE_ENV=production
      - PORT=8002

# 如果还有数据库或其他服务，也可以在这里添加
# ...
