services:
  frontend:
    build:
      target: frontend
    image: fullstack-blog-frontend:latest
    ports:
      - "3000:80"
    environment:
      - BACKEND_PORT=8002
    command: /bin/bash -c "envsubst '$$BACKEND_PORT' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && cat /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  backend:
    build:
      target: backend
    image: fullstack-blog-backend:latest
    ports:
      - "8002:8002"
    volumes:
      - ./app/backend/src/config/env.js:/usr/src/fullstack-blog/app/backend/src/config/env.js
      - ./app/backend/src/config/prod.env.js:/usr/src/fullstack-blog/app/backend/src/config/prod.env.js
    environment:
      - NODE_ENV=production
      - PORT=8002

# 如果还有数据库或其他服务，也可以在这里添加
# ...
