services:
  vite-vue3:
    build:
      target: vite-vue3-frontend
    image: ${DOCKER_REGISTRY}/${DOCKER_NAMESPACE}/fullstack-blog-vite-vue3:${VITE_VUE3_VERSION:-latest}
    ports:
      - "3000:80"
    environment:
      - BACKEND_PORT=8002
    command: /bin/bash -c "envsubst '$$BACKEND_PORT' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  webpack-vue3:
    build:
      target: webpack-vue3-frontend
    image: ${DOCKER_REGISTRY}/${DOCKER_NAMESPACE}/fullstack-blog-webpack-vue3:${WEBPACK_VUE3_VERSION:-latest}
    ports:
      - "3001:80"
    environment:
      - BACKEND_PORT=8002
    command: /bin/bash -c "envsubst '$$BACKEND_PORT' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  express-server:
    build:
      target: express-backend
    image: ${DOCKER_REGISTRY}/${DOCKER_NAMESPACE}/fullstack-blog-express:${EXPRESS_SERVER_VERSION:-latest}
    ports:
      - "8002:8002"
    volumes:
      - ./express-server/config/dev.env.js:/usr/src/fullstack-blog/app/express-server/src/config/dev.env.js
      - ./express-server/config/env.js:/usr/src/fullstack-blog/app/express-server/src/config/env.js
      - ./express-server/config/prod.env.js:/usr/src/fullstack-blog/app/express-server/src/config/prod.env.js
    environment:
      - NODE_ENV=production
      - PORT=8002

# 如果还有数据库或其他服务，也可以在这里添加
# ...
