services:
  frontend:
    image: fullstack-blog-frontend:latest
    ports:
      - "3000:3000"
    volumes:
      - ./app/frontend/src:/usr/src/fullstack-blog/app/frontend/src
      - ./app/frontend/vue.config.docker.js:/usr/src/fullstack-blog/app/frontend/vue.config.js
      - ./tsconfig.base.json:/usr/src/fullstack-blog/tsconfig.base.json
      - ./.prettierrc.json:/usr/src/fullstack-blog/.prettierrc.json
      - ./.prettierignore:/usr/src/fullstack-blog/.prettierignore
    environment:
      - NODE_ENV=development

  backend:
    image: fullstack-blog-backend:latest
    ports:
      - "8002:8002"
    volumes:
      - ./app/backend/src:/usr/src/fullstack-blog/app/backend/src
    environment:
      - NODE_ENV=development
      - PORT=8002

# 如果还有数据库或其他服务，也可以在这里添加
# ...
