FROM node:20-slim AS base

# 安装 Python 和构建工具
RUN apt-get update && apt-get install -y python3 make g++ \
    && rm -rf /var/lib/apt/lists/*

RUN npm i -g pnpm
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

FROM base AS build
COPY . /usr/src/app
WORKDIR /usr/src/app
# macos 15 运行下面这行会报错，所以上面加了 python3
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
RUN pnpm deploy --filter=vite-vue3 /app/vite-vue3
# RUN pnpm deploy --filter=cra-react18 /app/cra-react18
RUN pnpm deploy --filter=express-server /app/express-server
# RUN pnpm deploy --filter=nest-server /app/nest-server

FROM base AS vite-vue3-frontend
COPY --from=build /app/vite-vue3 /usr/src/fullstack-blog/app/vite-vue3
WORKDIR /usr/src/fullstack-blog/app/vite-vue3
EXPOSE 3000
CMD ["pnpm", "dev"]

# FROM base AS cra-react18-frontend
# COPY --from=build /app/cra-react18 /usr/src/fullstack-blog/app/cra-react18
# WORKDIR /usr/src/fullstack-blog/app/cra-react18
# EXPOSE 3000
# CMD ["pnpm", "dev"]

FROM base AS express-backend
RUN npm i -g pm2-dev
COPY --from=build /app/express-server /usr/src/fullstack-blog/app/express-server

# FROM base AS nestjs-backend
# COPY --from=build /app/nest-server /usr/src/fullstack-blog/app/nest-server
