# This is a basic workflow that is manually triggered

name: Manual Trigger Release Workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Remarks'
        # Default value if no value is explicitly provided
        default: 'trigger a release'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  trigger-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set node version to 16
        uses: actions/setup-node@v4
        with:
          node-version: 16
        
      - name: Create Release
        run: |
          yarn install
          yarn create-release

