name: Release

on:
  push:
    branches:
      - main
    paths:
      - .changeset/**

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Setup Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 9.4.0

      - name: Install Workspace Root Dependencies
        run: |
          pnpm install --workspace-root --frozen-lockfile

      - name: Create PR or Publish Release
        uses: changesets/action@v1
        with:
          version: pnpm version-bump
          publish: pnpm release
          title: "bot: version packages"
          commit: "chore: version packages"
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
