name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  GITHUB_TOKEN: ${{secrets.PERSONAL_TOKEN}}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Set Git User
        run: |
          git config --global user.email "1148121254@qq.com"
          git config --global user.name "cumt-robin"

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 9.4.0

      - name: Install Dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Create PR or Publish Release
        uses: changesets/action@v1
        with:
          version: pnpm version-bump
          publish: pnpm release
          title: "bot: version packages"
          commit: "chore: version packages"
          createGithubReleases: true
          setupGitUser: false
