name: vite-vue3-e2e

on:
  push:
    tags:
      - 'vite-vue3@*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.19.0

    - name: Setup pnpm
      uses: pnpm/action-setup@v4.0.0
      with:
        version: 9.4.0

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Install Playwright browsers
      working-directory: app/vite-vue3
      run: npx playwright install --with-deps

    - name: Build for preview
      working-directory: app/vite-vue3
      run: pnpm build-for-preview

    - name: Run Playwright tests
      working-directory: app/vite-vue3
      env:
        NODE_ENV: production
      run: pnpm test:e2e:ci
